# This is a sample TOML control file for the ScriptedBibleEditor
#
# Available commands are:
#
#   title = "My Control File Title"
#   description = "A longer description"
#
#   [commandTables]
#   tableName = "filepath"
#

title = "ScriptedBibleEditor OET-LV-OT Control File"
description = "To convert USFM files to create the draft OET-LV-OT"

inputFolder = "../../intermediateTexts/modified_source_glossed_OSHB_ESFM/"
inputFilenameTemplate = "BBB_gloss.ESFM"

outputFolder = "../../intermediateTexts/auto_edited_OT_ESFM/"
outputFilenameTemplate = "OET-LV_BBB.ESFM"
clearOutputFolder = true # Removes the folder and recreates it if createOutputFolder is true (else deletes all files in the folder)
createOutputFolder = true

applyOrder = "AllTablesFirst"

# Command tables are applied in the given order
[commandTables]
wordingAdjustments = "wordingAdjustments.commandTable.tsv"
adjustCapitalisation = "adjustCapitalisation.commandTable.tsv"
adjustPunctuation = "adjustPunctuation.commandTable.tsv"
changeFromUSSpelling = "changeFromUSSpelling.commandTable.tsv"
restoreNames = "restoreNames.commandTable.tsv"
#fixGlossPre = "fixGlossPre.commandTable.tsv"
#fixGlossHelpers = "fixGlossHelpers.commandTable.tsv"
#fixGlossPost = "fixGlossPost.commandTable.tsv"
finalCleanup = "finalCleanup.commandTable.tsv"
